import "./images/staff/scaled_dawn_buker.jpg";
import "./images/staff/scaled_mike_carroll2019.jpg";
import "./images/staff/scaled_mike_modica2019.jpg";
import "./images/staff/scaled_mykaela_blades2019.jpg";
import "./images/staff/scaled_nathan_buker2019.jpg";
import "./images/staff/scaled_Pastor_Dawn_09.jpg";
import "./images/staff/scaled_patt_lott2019.jpg";
import "./images/staff/scaled_susan_john_anderson2019.jpg";
import "./images/staff/placeholder.jpg";
